apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail
      automountServiceAccountToken: true
      containers:
        - name: promtail
          image: grafana/promtail:3.6.3
          args:
            - -config.file=/etc/promtail/promtail.yaml
            - -log.level=info
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: varlog
              mountPath: /var/log
              mountPropagation: HostToContainer
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              mountPropagation: HostToContainer
              readOnly: true
          securityContext:
            privileged: true
            runAsUser: 0
      volumes:
        - name: config
          configMap:
            name: promtail-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers